### ISSUE TITLE
this is not a issue

### ISSUE THREAD

**Issue by Cloddd** [JiminyKroket/Invhud#31]
this is more a request than a bug, the inventory works flawless, no bug no types of lag, perfect, a thing u can add is the accessories directly to the inventory, the possibility to add, remove accessories and save it properly

**Comment by Cloddd** [comment]
i know there much scripts made around the github, the problem is that is not esx and isnt consistent

**Comment by JiminyKroket** [comment]
My accessory pack available at modit.store allows exactly that

**Comment by Cloddd** [comment]
accessories for weapon i mean

**Comment by Cloddd** [comment]
attachments

**Comment by JiminyKroket** [comment]
Almost exactly that actually sorry. It uses standard esx menu but allows
saving accessories and even using bag specific inventories

**Comment by JiminyKroket** [comment]
Ah

**Comment by Cloddd** [comment]
it will be very cool and unique to add in this inventory

**Comment by JiminyKroket** [comment]
It might be something i look into but is a big undertaking

**Comment by Cloddd** [comment]
im sure u can do it, i ve saw some your scripts on the store and are very interesting

**Comment by JiminyKroket** [comment]
I appreciate the support. Unfortunately the can do it is not the issue on
something like this. It's the when can I do it.

**Comment by JiminyKroket** [comment]
Storing weapon attachments across all inventories, for every esx version is
gonna be an extremely detailed process. It's legitimately going to take
hours of just finding all the information I'm going to need. Then probably
a similar amount of time to get an initial system set up. Followed up by
days if not weeks of debugging and issue solving. As you said, invhud is
pretty flawless(not 100% im sure) but thats because i dedicate a lot of
time to each portion.
