### ISSUE TITLE
Notifications in shops

### ISSUE THREAD

**Issue by maxcamorra** [JiminyKroket/Invhud#58]
How to add a notification when I enter the shop marker?

**Comment by JiminyKroket** [comment]
Loop through the shops and check the distance from the player if its like 2
then notify them

**Comment by maxcamorra** [comment]
can you tell me where exactly?

**Comment by JiminyKroket** [comment]
In the client.lua

**Comment by maxcamorra** [comment]
![image](https://user-images.githubusercontent.com/78707245/114282695-ac5b0800-9a45-11eb-81f6-f4eef38195b4.png)
I have put there under the if dis < 1.5 my notify but it only shows when i enter f2 for entering the shop

**Comment by JiminyKroket** [comment]
Yes because that is the loop ran when the player is standing in the shop
and opens their inventory. Read what I type and Google it if you do not
understand. You need to look all of the shops and check the distance from
the player. If the distance is less than like 2, then notify them. Invhud
does NOT have useless loops running all the time wasting resources. You
need to code your own specifically to do that.

**Comment by JiminyKroket** [comment]
You need to loop(why did auto correct correct a correct word wtf)

**Comment by JiminyKroket** [comment]
Added, thoroughly adjust config.
